Algoritmo "semnome"
Var

 nome: caracter
 endereco: caracter
 telefone: inteiro
 cidade: caracter
 cep: inteiro

Inicio

EscrevaL("Qual seu nome ?")
Leia(nome)
EscrevaL("Qual seu endereço ?")
Leia(endereco)
EscrevaL("Qual seu telefone ?")
Leia(telefone)
EscrevaL("Qual sua cidade ?")
Leia(cidade)
EscrevaL("Qual seu cep ?")
Leia(cep)

EscrevaL("Meu nome é ",nome ," moro na cidade de ",cidade ," com o cep:",cep ," no endereço: ",endereco ," telefone:",telefone)

Fimalgoritmo