Algoritmo "semnome"
Var

paes, bolos, totalDePao, totalDeBolo, apurado: real

Inicio

      EscrevaL("Digite a quantidade de pães: ")
      Leia(paes)
      EscrevaL("Digite a quantidade de bolos: ")
      Leia(bolos)

      totalDePao <- paes * 0.35
      totalDeBolo <- bolos * 5.00

      EscrevaL(paes, " pães =", totalDePao)
      EscrevaL(bolos, " bolos =", totalDEBolo)
      EscrevaL("Total do apurado: ", totalDePao + totalDeBolo)

Fimalgoritmo